name: Events Demo 1
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output Event Data
        run: echo "${{ toJSON(github.event) }}"
      