name: First Work Flow
on: workflow_dispatch
jobs:
     first-job:
          runs-on: ubuntu-latest
          steps:
               - name: Print Greeting
                 run: |
                      QUESTION="What is your name?"
                      NAME
                      echo $QUESTION
                      read $NAME;
                      echo "Hello $NAME"
